#!/usr/bin/env bash
# Configure Nginx server to give error
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
chmod -R 755 /var/www
echo 'Hello World' > /var/www/html/index.html

server_config=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                try_files \$uri \$uri/ =404;
        }
        if (\$request_filename ~ redirect_me){
            rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
        }
        error_page 404 /404.html;
        location  /404.html {
            internal;
        }
        
}
"

echo "$server_config" > /etc/nginx/sites-available/default

sudo service nginx restart
