#!/usr/bin/env bash
# displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line
COUNT=1
while [ $COUNT -le 10 ];
do
    echo "Best School"
    if [ $COUNT -eq 9 ]; then
        echo "Hi"
    fi
    COUNT=$((COUNT+1))
done