#!/usr/bin/env bash
#Block certain ports while allowing port 22, 443 and 80

sudo apt install -y ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo ufw enable
